import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Form from '../components/Form'
import styles from '../styles/Home.module.css'
import axios from 'axios'
// https://covid19.ddc.moph.go.th/api/Cases/today-cases-by-provinces
export default function Home() {

  const [covidProvinces, setCovidProvinces] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(true)
    axios
      .get('https://covid19.ddc.moph.go.th/api/Cases/today-cases-by-provinces')
      .then((response) => response.data)
      .then((data) => {
        setCovidProvinces(data)
        setLoading(false)
      })
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form props={covidProvinces}/>
    </div>
  )
}
